# Generated by Django 5.2.5 on 2025-08-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmappedterm',
            name='matched_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phrases.termvariant'),
        ),
    ]
