# Generated by Django 5.2.5 on 2025-08-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_alter_unmappedterm_matched_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmappedterm',
            name='common_similarity',
            field=models.BooleanField(default=True, help_text='Is the Term Similar to One of Its Concept Variants?'),
        ),
    ]
