# Generated by Django 5.2.5 on 2025-08-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0003_unmappedterm_common_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconcept',
            name='ai_used',
            field=models.BooleanField(default=False),
        ),
    ]
