# Generated by Django 4.0.10 on 2024-03-06 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='لینک مورد علاقه برای کیس خود را وارد کنید. تلاش کنید لینکتان گویا و دقیق باشد، پس از این توانایی تغییر آن را نخواهید داشت.', max_length=40, unique=True, verbose_name='Link')),
                ('title', models.CharField(max_length=50)),
                ('cat', models.CharField(blank=True, choices=[('ریه', 'ریه'), ('هماتولوژی و انکولوژی', 'هماتولوژی و انکولوژی'), ('روماتولوژی', 'روماتولوژی'), ('غدد', 'غدد'), ('گوارش', 'گوارش'), ('نفرولوژی', 'نفرولوژی'), ('جنرال', 'جنرال'), ('قلب', 'قلب'), ('پوست', 'پوست'), ('اطفال', 'اطفال'), ('زنان', 'زنان'), ('اعصاب', 'اعصاب'), ('روان', 'روان'), ('ENT', 'ENT'), ('عفونی', 'عفونی'), ('چشم', 'چشم'), ('مسمومین', 'مسمومین')], max_length=100, null=True, verbose_name='دسته:')),
                ('description', models.CharField(blank=True, help_text='خلاصه\u200cای برای نشان دادن در صفحۀ اصلی که می\u200cتواند از عنوان طولانی\u200cتر باشد (تا دویست حرف).', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pretext', models.TextField(blank=True, help_text='اگر خواستید، می\u200cتوانید مقدمه\u200cای دربارۀ شرح\u200cحال خود بنویسید.', null=True)),
                ('gender', models.CharField(choices=[('آقا', 'Male'), ('خانم', 'Female'), ('دیگر', 'Other')], default='O', max_length=5)),
                ('location', models.CharField(choices=[('مطب', 'مطب'), ('درمانگاه', 'درمانگاه'), ('اورژانس', 'اورژانس'), ('بخش', 'بخش')], default='ROT', max_length=10)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('dwelling', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField(default=40)),
                ('marriage', models.CharField(blank=True, choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد'), ('همسر فوت شده', 'همسر فوت شده'), ('جداشده', 'جداشده')], max_length=15, null=True)),
                ('doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('reliability', models.CharField(blank=True, choices=[('5', '5/5'), ('4', '4/5'), ('3', '3/5'), ('2', '2/5'), ('1', '1/5')], max_length=1, null=True)),
                ('setting', models.CharField(blank=True, max_length=30, null=True)),
                ('PR', models.DecimalField(blank=True, decimal_places=0, default=70, max_digits=3, null=True)),
                ('BP_S', models.DecimalField(blank=True, decimal_places=0, default=120, max_digits=3, null=True, verbose_name='Systolic BP')),
                ('BP_D', models.DecimalField(blank=True, decimal_places=0, default=80, max_digits=3, null=True, verbose_name='Diastolic BP')),
                ('RR', models.DecimalField(blank=True, decimal_places=0, default=18, max_digits=2, null=True)),
                ('SPO2_O', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='SPO2 With Oxygen')),
                ('SPO2_N', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='SPO2 Without Oxygen')),
                ('Temp', models.DecimalField(blank=True, decimal_places=0, default=37, max_digits=2, null=True, verbose_name='Temperature')),
                ('cc', models.CharField(default='', max_length=100, verbose_name='Cheif Complaint')),
                ('pi', models.TextField(default='', verbose_name='Present Illness')),
                ('pmh', models.TextField(blank=True, null=True, verbose_name='Past Medical History')),
                ('drg', models.TextField(blank=True, null=True, verbose_name='Drugs and Addictions')),
                ('sh', models.TextField(blank=True, null=True, verbose_name='Social History')),
                ('fh', models.TextField(blank=True, null=True, verbose_name='Family History')),
                ('alg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Allergies')),
                ('phe', models.TextField(blank=True, null=True, verbose_name='Physical Examinations and Review of Systems')),
                ('dat', models.TextField(blank=True, help_text='Including Previous Lab Data and Images and ECGs.', null=True, verbose_name='Paraclinic Data')),
                ('summary', models.TextField(blank=True, null=True)),
                ('pdx', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Dx')),
                ('act', models.TextField(blank=True, null=True, verbose_name='Actions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Days After Admission:')),
                ('text', models.TextField(help_text='توجه کنید که نت\u200cها در حال حاضر، قابل تغییر یا پاکسازی نیستند.', verbose_name='Note')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
