# Generated by Django 4.0.10 on 2024-03-13 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ddx',
            field=models.TextField(blank=True, help_text='دلیل رد تشخیص\u200cها و اقدام\u200cها جهت رسیدن به تشخیص قطعی را هم می\u200cتوانید اینجا ذکر کنید.', null=True, verbose_name='تشخیص\u200cهای افتراقی'),
        ),
        migrations.AddField(
            model_name='case',
            name='post_text',
            field=models.TextField(blank=True, help_text='می\u200cتوانید توضیحات بیشتر که در شرح\u200cحال قرار نمی\u200cگیرند و همچنین اطلاعات بیشتر دربارۀ بیماری را در اینجا ذکر کنید.', null=True, verbose_name='توضیح پایانی'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='BP_D',
            field=models.DecimalField(blank=True, decimal_places=0, default=80, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=3, null=True, verbose_name='Diastolic BP'),
        ),
        migrations.AlterField(
            model_name='case',
            name='BP_S',
            field=models.DecimalField(blank=True, decimal_places=0, default=120, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=3, null=True, verbose_name='Systolic BP'),
        ),
        migrations.AlterField(
            model_name='case',
            name='RR',
            field=models.DecimalField(blank=True, decimal_places=0, default=18, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='SPO2_N',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=3, null=True, verbose_name='SPO2 Without Oxygen'),
        ),
        migrations.AlterField(
            model_name='case',
            name='SPO2_O',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=3, null=True, verbose_name='SPO2 With Oxygen'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Temp',
            field=models.DecimalField(blank=True, decimal_places=0, default=37, help_text='می\u200cتوانید با حذف کردن مقدار پیش\u200cفرض، آن را خالی بگذارید.', max_digits=2, null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='case',
            name='act',
            field=models.TextField(blank=True, null=True, verbose_name='اقدامات'),
        ),
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='case',
            name='alg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حساسیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cc',
            field=models.CharField(default='', max_length=100, verbose_name='شکایت اصلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dat',
            field=models.TextField(blank=True, help_text='داده\u200cهای آزمایشگاهی و گزارش\u200cهای تصویربرداری، اکوگرافی، نوار قلب و ...', null=True, verbose_name='داده\u200cهای پاراکلینیکی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, help_text='خلاصه\u200cای برای نشان دادن در صفحۀ اصلی که می\u200cتواند از عنوان طولانی\u200cتر باشد (تا دویست حرف).', max_length=200, null=True, verbose_name='توضیح:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='doctor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پزشک درمانگر'),
        ),
        migrations.AlterField(
            model_name='case',
            name='drg',
            field=models.TextField(blank=True, null=True, verbose_name='داروها'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dwelling',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل زندگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fh',
            field=models.TextField(blank=True, null=True, verbose_name='سابقۀ بیماری\u200cهای خانواده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('آقا', 'Male'), ('خانم', 'Female'), ('دیگر', 'Other')], default='O', max_length=5, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پیشه (شغل)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(choices=[('مطب', 'مطب'), ('درمانگاه', 'درمانگاه'), ('اورژانس', 'اورژانس'), ('بخش', 'بخش')], default='ROT', max_length=10, verbose_name='محل زندگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='marriage',
            field=models.CharField(blank=True, choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد'), ('همسر فوت شده', 'همسر فوت شده'), ('جداشده', 'جداشده')], max_length=15, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pdx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تشخیص اولیه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='phe',
            field=models.TextField(blank=True, null=True, verbose_name='معاینۀ فیزیکی و بررسی دستگاه\u200cها'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pi',
            field=models.TextField(default='', verbose_name='شرح بیماری فعلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pmh',
            field=models.TextField(blank=True, null=True, verbose_name='شرح بیماری\u200cهای گذشته'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pretext',
            field=models.TextField(blank=True, help_text='اگر خواستید، می\u200cتوانید مقدمه\u200cای دربارۀ شرح\u200cحال خود بنویسید.', null=True, verbose_name='پیش\u200cمتن'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reliability',
            field=models.CharField(blank=True, choices=[('5', '5/5'), ('4', '4/5'), ('3', '3/5'), ('2', '2/5'), ('1', '1/5')], max_length=1, null=True, verbose_name='میزان قابل اعتماد بودن بیمار از 5'),
        ),
        migrations.AlterField(
            model_name='case',
            name='setting',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='مرکز درمانی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sh',
            field=models.TextField(blank=True, help_text='مصرف مواد مخدر، الکل، وضعیت نظام وظیفه، شغل، روابط اجتماعی و جنسی و ...', null=True, verbose_name='شرح حال اجتماعی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='منبع شرح حال'),
        ),
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصۀ شرح حال و معاینه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان:'),
        ),
    ]
