# Generated by Django 4.0.10 on 2024-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_ddx_case_post_text_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lang',
            field=models.CharField(choices=[('Fa', 'Fa')], default='Fa', max_length=2, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='case',
            name='ros',
            field=models.TextField(blank=True, null=True, verbose_name='بررسی دستگاه\u200cها'),
        ),
        migrations.AlterField(
            model_name='case',
            name='phe',
            field=models.TextField(blank=True, null=True, verbose_name='معاینۀ بدنی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
