# Generated by Django 4.0.10 on 2024-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_picasso'),
    ]

    operations = [
        migrations.AddField(
            model_name='picasso',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
