# Generated by Django 4.0.10 on 2024-03-21 15:09

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_picasso_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(choices=[('مطب', 'مطب'), ('درمانگاه', 'درمانگاه'), ('اورژانس', 'اورژانس'), ('بخش', 'بخش')], default='ROT', max_length=10, verbose_name='مکان مراجعه'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cases.models.user_directory_path),
        ),
    ]
