# Generated by Django 4.0.10 on 2024-03-22 09:58

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_location_alter_picasso_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cases/hx/uploads/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='image',
            field=models.ImageField(upload_to=cases.models.user_directory_path),
        ),
    ]
