# Generated by Django 4.0.10 on 2024-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_choice_case_choice_picasso_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, to='cases.choice'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, to='cases.choice'),
        ),
    ]
