# Generated by Django 4.0.10 on 2024-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_picasso_picasso_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(to='cases.tag'),
        ),
    ]
