# Generated by Django 4.0.10 on 2024-03-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_tag_case_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('item_abbr', models.CharField(help_text='eg: WBC', max_length=16, verbose_name='مخفف نام')),
                ('item_full', models.CharField(blank=True, help_text='eg: White Blood Cell', max_length=50, null=True, verbose_name='نام کامل')),
                ('tst_category', models.CharField(choices=[('Blood', 'Blood'), ('Biochemistry', 'Biochemistry'), ('U/A', 'U/A'), ('Serologic', 'Serologic'), ('Other', 'Other')], default='Blood', max_length=25, verbose_name='دسته')),
                ('value', models.CharField(default='', max_length=8, verbose_name='مقدار')),
                ('unit', models.CharField(default='10^3/µL', max_length=16, verbose_name='واحد')),
                ('ref_rng', models.CharField(default='', help_text='eg: 3.8 - 5.4', max_length=16, verbose_name='بازۀ مرجع')),
                ('flag', models.CharField(choices=[('NL', 'NL'), ('H', 'H'), ('L', 'L'), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Other', 'Other')], default='Other', max_length=25, verbose_name='دسته')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
