# Generated by Django 4.0.10 on 2024-03-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_labtestitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestitem',
            old_name='tst_category',
            new_name='category',
        ),
    ]
