# Generated by Django 4.0.10 on 2024-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_rename_tst_category_labtestitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestitem',
            name='flag',
            field=models.CharField(choices=[('NL', 'NL'), ('H', 'H'), ('L', 'L'), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Other', 'Other')], default='Other', max_length=25, verbose_name='وضعیت'),
        ),
    ]
