# Generated by Django 4.0.10 on 2024-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_caseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseimage',
            name='type',
            field=models.CharField(choices=[('ECG', 'ECG'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('Ultra-Sound', 'Ultra-Sound'), ('Other', 'Other')], default='Other', max_length=16),
        ),
    ]
