# Generated by Django 4.0.10 on 2024-03-29 13:02

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_caseimage_text_caseimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(upload_to=cases.models.user_directory_path_hx, verbose_name='آپلود تصویر'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='text',
            field=models.TextField(blank=True, help_text='توضیح یا گزارش تصویر', null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='type',
            field=models.CharField(choices=[('ECG', 'ECG'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('Ultra-Sound', 'Ultra-Sound'), ('Other', 'Other')], default='Other', max_length=16, verbose_name='نوع داده'),
        ),
    ]
