# Generated by Django 4.0.10 on 2024-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_caseimage_verified_alter_caseimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
