# Generated by Django 4.0.10 on 2024-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_caseimage_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hi')),
            ],
        ),
        migrations.RenameModel(
            old_name='CaseImage',
            new_name='ImageCase',
        ),
        migrations.RemoveField(
            model_name='case',
            name='choice',
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cases.tag'),
        ),
        migrations.DeleteModel(
            name='LabTestItem',
        ),
    ]
