# Generated by Django 4.0.10 on 2024-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_delete_rien_remove_case_bp_d_remove_case_bp_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
