# Generated by Django 4.0.10 on 2024-03-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_rien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='picasso',
        ),
    ]
