# Generated by Django 4.0.10 on 2024-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_note_review_suggest_delete_rien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picasso',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='I want to DELETE this Picasso.'),
        ),
    ]
