# Generated by Django 4.0.10 on 2024-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_picasso_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
