# Generated by Django 4.0.10 on 2024-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_alter_note_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='suggests',
            field=models.ManyToManyField(blank=True, null=True, to='cases.suggest'),
        ),
        migrations.AddField(
            model_name='note',
            name='suggests',
            field=models.ManyToManyField(blank=True, null=True, to='cases.suggest'),
        ),
        migrations.AddField(
            model_name='picasso',
            name='suggests',
            field=models.ManyToManyField(blank=True, null=True, to='cases.suggest'),
        ),
    ]
