# Generated by Django 4.0.10 on 2024-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_alter_case_suggests_alter_case_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='suggests',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', null=True, to='cases.suggest'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', null=True, to='cases.tag'),
        ),
    ]
