# Generated by Django 4.0.10 on 2024-04-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_alter_case_suggests_alter_case_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cases/uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='cat',
        ),
        migrations.AlterField(
            model_name='case',
            name='cc',
            field=models.CharField(default='', help_text='Chief Complaint', max_length=100, verbose_name='شکایت اصلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fh',
            field=models.TextField(blank=True, help_text='Family History', null=True, verbose_name='سابقۀ بیماری\u200cهای خانواده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='phe',
            field=models.TextField(blank=True, help_text='Physical Examinations', null=True, verbose_name='معاینۀ بدنی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pi',
            field=models.TextField(default='', help_text='Present Illness', verbose_name='شرح بیماری فعلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pmh',
            field=models.TextField(blank=True, help_text='Past Medical History', null=True, verbose_name='شرح بیماری\u200cهای گذشته'),
        ),
        migrations.AlterField(
            model_name='case',
            name='ros',
            field=models.TextField(blank=True, help_text='Review of Systems', null=True, verbose_name='بررسی دستگاه\u200cها'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='case',
            name='rts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.rotation'),
        ),
    ]
