# Generated by Django 4.0.10 on 2024-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_rotation_remove_case_cat_alter_case_cc_alter_case_fh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dwelling',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='محل زندگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='پیشه (شغل)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(choices=[('مطب', 'مطب'), ('درمانگاه', 'درمانگاه'), ('اورژانس', 'اورژانس'), ('بخش', 'بخش')], default='بخش', max_length=10, verbose_name='مکان مراجعه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='marriage',
            field=models.CharField(blank=True, choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد'), ('همسر فوت شده', 'همسر فوت شده'), ('جداشده', 'جداشده')], default='متاهل', max_length=15, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='منبع شرح حال'),
        ),
    ]
