# Generated by Django 4.0.10 on 2024-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_labgraphselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgraphselection',
            name='description',
            field=models.TextField(blank=True, help_text='Optional', null=True),
        ),
    ]
