# Generated by Django 4.0.10 on 2024-06-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_labgraphselection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagecase',
            name='type',
            field=models.CharField(choices=[('ECG', 'ECG'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('Ultra-Sound', 'Ultra-Sound'), ('CT Scan', 'CT Scan'), ('Other', 'Other')], default='Other', max_length=16, verbose_name='نوع داده'),
        ),
        migrations.AlterField(
            model_name='imagecase',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
