# Generated by Django 4.0.10 on 2024-06-25 15:57

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_alter_case_verified_alter_imagecase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgraphselection',
            name='zero',
            field=models.BooleanField(default=False, help_text='اگر می\u200cخواهید عدد صفر هم در نمودار درج شود، این تیک را بزنید', verbose_name='رسم از صفر'),
        ),
        migrations.AddField(
            model_name='picasso',
            name='inappropriate',
            field=models.BooleanField(default=False, help_text='اگر این تصویر می\u200cتواند برای بخشی از جامعۀ هدف آزاردهنده باشد، این تیک را بزنید تا به طور واضح در صفحۀ نخست سایت به نمایش در نیاید.', verbose_name='آزاردهنده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(help_text='لینک مورد علاقه برای کیس خود را وارد کنید. تلاش کنید لینکتان گویا و دقیق باشد، پس از این توانایی تغییر آن را نخواهید داشت. استفاده از فاصله (Space) مجاز نیست.', max_length=40, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این یادداشت یک آدرس مرتبط ایجاد کنید. برای مثال ems-01.', unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این تصویر یک آدرس مرتبط ایجاد کنید. برای مثال cushing-striae-01.', unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=builtins.id, unique=True),
        ),
    ]
