# Generated by Django 4.0.10 on 2024-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_alter_note_slug_alter_picasso_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این یادداشت یک آدرس مرتبط ایجاد کنید. برای مثال ems-01.', unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این تصویر یک آدرس مرتبط ایجاد کنید. برای مثال cushing-striae-01.', unique=True, verbose_name='Link'),
        ),
    ]
