# Generated by Django 4.0.10 on 2024-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_alter_note_slug_alter_picasso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(help_text='لینک مورد علاقه برای کیس خود را وارد کنید. تلاش کنید لینکتان گویا و دقیق باشد، پس از این توانایی تغییر آن را نخواهید داشت. استفاده از فاصله (Space) مجاز نیست.', max_length=40, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این یادداشت یک آدرس مرتبط ایجاد کنید. برای مثال ems-01.', unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='slug',
            field=models.SlugField(help_text='برای دسترسی به این تصویر یک آدرس مرتبط ایجاد کنید. برای مثال cushing-striae-01.', unique=True, verbose_name='لینک'),
        ),
    ]
