# Generated by Django 4.0.10 on 2024-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_aireqreslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireqreslog',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('PI', 'PI'), ('ROS', 'ROS'), ('PhE', 'PhE'), ('Sum', 'Sum'), ('DDx', 'DDx'), ('Act', 'Act')], max_length=10, null=True),
        ),
    ]
