# Generated by Django 4.0.10 on 2025-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_aireqreslog_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_pedi',
            field=models.BooleanField(default=False, verbose_name='آیا کیس کودک است؟'),
        ),
    ]
