# Generated by Django 5.2.5 on 2025-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0044_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='choice',
            field=models.ManyToManyField(to='cases.choice'),
        ),
        migrations.AlterField(
            model_name='case',
            name='suggests',
            field=models.ManyToManyField(help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.suggest'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='choice',
            field=models.ManyToManyField(to='cases.choice'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='cases.tag'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='choice',
            field=models.ManyToManyField(to='cases.choice'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='suggests',
            field=models.ManyToManyField(to='cases.suggest'),
        ),
        migrations.AlterField(
            model_name='picasso',
            name='tags',
            field=models.ManyToManyField(to='cases.tag'),
        ),
    ]
