# Generated by Django 5.2.5 on 2025-10-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_alter_case_choice_alter_case_suggests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='born_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='case',
            name='fdx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تشخیص پایانی'),
        ),
        migrations.AddField(
            model_name='case',
            name='previous_data',
            field=models.TextField(blank=True, help_text='داده\u200cهای آزمایشگاهی و گزارش\u200cهای تصویربرداری، اکوگرافی، نوار قلب و ... که پیش از مراجعه به دست آمده\u200cاند.', null=True, verbose_name='داده\u200cهای پیش از مراجعۀ بیمار'),
        ),
        migrations.AddField(
            model_name='case',
            name='professor_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagecase',
            name='is_old',
            field=models.BooleanField(default=False, verbose_name='آیا داده مربوط به مراجعات پیشین است؟'),
        ),
        migrations.AlterField(
            model_name='case',
            name='drg',
            field=models.TextField(blank=True, null=True, verbose_name='داروها و حساسیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dwelling',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل زندگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پیشه (شغل)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='post_text',
            field=models.TextField(blank=True, help_text='می\u200cتوانید توضیحات بیشتر که در شرح\u200cحال قرار نمی\u200cگیرند و همچنین اطلاعات بیشتر دربارۀ بیماری را در اینجا ذکر کنید.', null=True, verbose_name='توضیح پایانی و بحث'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sh',
            field=models.TextField(blank=True, help_text='مصرف مواد مخدر، الکل، وضعیت نظام وظیفه، شغل، روابط اجتماعی و جنسی و ...', null=True, verbose_name='شرح حال اجتماعی و عادات'),
        ),
        migrations.AddField(
            model_name='case',
            name='cc_tags',
            field=models.ManyToManyField(help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.cccategory'),
        ),
        migrations.AddField(
            model_name='case',
            name='dx_tags',
            field=models.ManyToManyField(help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.dxcategory'),
        ),
    ]
