# Generated by Django 5.2.5 on 2025-11-02 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_cccategory_dxcategory_case_born_city_case_fdx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_professor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='professor_post_text',
            field=models.TextField(blank=True, help_text='می\u200cتوانید توضیحات بیشتر که در شرح\u200cحال قرار نمی\u200cگیرند و همچنین اطلاعات بیشتر دربارۀ بیماری را در اینجا ذکر کنید.', null=True, verbose_name='توضیح پایانی و بحث'),
        ),
        migrations.AlterField(
            model_name='case',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('time_written', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case')),
            ],
        ),
    ]
