# Generated by Django 5.2.5 on 2025-11-02 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_case_professor_case_professor_post_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'professor_profile': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='منبع شرح حال'),
        ),
    ]
