# Generated by Django 5.2.5 on 2025-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0048_alter_case_professor_alter_case_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cc_tags',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.cccategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='choice',
            field=models.ManyToManyField(blank=True, to='cases.choice'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dx_tags',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.dxcategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='suggests',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.suggest'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='هم می\u200cتوانید خالی بگذارید و هم می\u200cتوانید چند مورد را انتخاب کنید (با نگه\u200cداشتن Ctrl در ویندوز).', to='cases.tag'),
        ),
    ]
