# Generated by Django 5.2.5 on 2025-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0049_alter_case_cc_tags_alter_case_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_university_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='act',
            field=models.TextField(blank=True, help_text='می\u200cتوانید اقدامات انجام شده برای بیمار را اینجا لیست کنید. شامل آزمایش\u200cها، عکس\u200cبرداری\u200cها و سایر اقدامات', null=True, verbose_name='اقدامات'),
        ),
        migrations.AlterField(
            model_name='case',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(blank=True, help_text='می\u200cتوانید Problem List بیمار را اینجا بنویسید.', null=True, verbose_name='خلاصۀ شرح حال و معاینه'),
        ),
    ]
