# Generated by Django 5.2.5 on 2025-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0050_case_is_university_case_alter_case_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_professor_turn',
            field=models.BooleanField(default=True),
        ),
    ]
