# Generated by Django 5.2.5 on 2025-11-07 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0051_case_is_professor_turn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_professor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
