# Generated by Django 5.2.5 on 2025-11-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_education_location_scientificgrade_section_and_more'),
        ('cases', '0054_alter_case_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_professor', to='accounts.professorprofile'),
        ),
    ]
