# Generated by Django 4.0.10 on 2025-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblock',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keyfeatureblock',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mcqblock',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pairingblock',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textblock',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to='steps/images/'),
        ),
    ]
