# Generated by Django 4.0.10 on 2025-05-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_race_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='steps.race')),
            ],
            options={
                'unique_together': {('race', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
