# Generated by Django 4.0.10 on 2025-05-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_record_delete_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steps.race'),
        ),
    ]
