# Generated by Django 4.0.10 on 2025-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion
import steps.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('steps', '0005_step_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('none', 'None')], max_length=16)),
                ('next_block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InteractiveStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.step')),
            ],
            options={
                'verbose_name': 'Interactive Step',
            },
            bases=('steps.step',),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to=steps.models.step_image_upload_path),
        ),
        migrations.CreateModel(
            name='InteractiveImageBlock',
            fields=[
                ('interactiveblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.interactiveblock')),
                ('image', models.ImageField(upload_to=steps.models.step_image_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('next_block_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.interactiveblock',),
        ),
        migrations.CreateModel(
            name='InteractiveImageOption',
            fields=[
                ('interactiveoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.interactiveoption')),
                ('image', models.ImageField(upload_to=steps.models.step_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.interactiveoption',),
        ),
        migrations.CreateModel(
            name='InteractiveQuestionBlock',
            fields=[
                ('interactiveblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.interactiveblock')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=steps.models.step_image_upload_path)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.interactiveblock',),
        ),
        migrations.CreateModel(
            name='InteractiveTextBlock',
            fields=[
                ('interactiveblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.interactiveblock')),
                ('content', models.TextField()),
                ('next_block_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.interactiveblock',),
        ),
        migrations.CreateModel(
            name='InteractiveTextOption',
            fields=[
                ('interactiveoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.interactiveoption')),
                ('text', models.CharField(max_length=255)),
                ('response', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.interactiveoption',),
        ),
        migrations.AddField(
            model_name='interactiveblock',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_blocks', to='steps.interactivestep'),
        ),
        migrations.AddField(
            model_name='interactiveoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='steps.interactivequestionblock'),
        ),
        migrations.AlterUniqueTogether(
            name='interactiveblock',
            unique_together={('step', 'number')},
        ),
    ]
