# Generated by Django 5.2.5 on 2025-08-14 06:40

import steps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_interactiveblock_interactiveoption_interactivestep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactiveblock',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='interactiveimageblock',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interactiveimageblock',
            name='parse_md',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactiveimageoption',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interactiveimageoption',
            name='parse_md_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactivequestionblock',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interactivequestionblock',
            name='parse_md',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactivetextblock',
            name='parse_md',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactivetextoption',
            name='parse_md_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interactiveimageoption',
            name='image',
            field=models.ImageField(upload_to=steps.models.step_option_image_upload_path),
        ),
    ]
