# Generated by Django 5.2.5 on 2025-08-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_alter_unmappedterm_matched_term'),
        ('steps', '0011_alter_interactiveblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_md',
            field=models.BooleanField(default=False, help_text='Parse block text as a markdown text.', verbose_name='Parse as MD'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='alt_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MonoTextCheckBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='steps.block')),
                ('visible', models.BooleanField(default=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('xp', models.IntegerField(default=10)),
                ('answer_concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phrases.medicalconcept')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('steps.block',),
        ),
    ]
