# Generated by Django 5.2.5 on 2025-10-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0013_record_user_alter_record_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='steps.course'),
        ),
    ]
