# Generated by Django 5.2.5 on 2025-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0014_alter_courseregistration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open_for_answering',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='open_for_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='visible_when_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
