# Generated by Django 5.2.5 on 2025-10-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0014_record_course_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
