# Generated by Django 5.2.5 on 2025-10-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0015_course_open_for_answering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score_correction',
            field=models.BooleanField(default=False),
        ),
    ]
