# Generated by Django 5.2.5 on 2025-10-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0016_alter_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='course',
        ),
        migrations.RemoveField(
            model_name='record',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
