# Generated by Django 5.2.5 on 2025-10-30 08:15

import django.utils.timezone
import steps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0016_course_score_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=steps.models.step_image_upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='block',
            name='img_alt_txt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Alt Text'),
        ),
    ]
