# Generated by Django 5.2.5 on 2025-10-31 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0017_block_date_added_block_img_block_img_alt_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_writen', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('race_score', models.PositiveSmallIntegerField(null=True)),
                ('survey_score', models.PositiveSmallIntegerField(null=True)),
                ('text_box', models.TextField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steps.race')),
            ],
        ),
    ]
