# Generated by Django 5.2.5 on 2025-10-20 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0017_remove_race_course_remove_record_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_led', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='courses_joined', through='steps.CourseRegistration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='steps.course'),
        ),
        migrations.AddField(
            model_name='race',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='races', to='steps.course'),
        ),
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steps.course'),
        ),
    ]
