# Generated by Django 4.0.10 on 2024-03-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Basic Sciences', 'Basic Sciences'), ('Physiopathology', 'Physiopathology'), ('Medical Extern', 'Medical Extern'), ('Medical Intern', 'Medical Intern'), ('General Practicioner', 'General Practicioner'), ('Medical Resident', 'Medical Resident'), ('Medical Specialist', 'Medical Specialist'), ('Fellowship', 'Fellowship'), ('Superspecialist', 'Superspecialist')], help_text='Your current degree. Leave empty if not Medical Doctor/Student.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, choices=[('MUMS', 'علوم پزشکی مشهد'), ('TUMS', 'علوم پزشکی تهران'), ('NKUMS', 'علوم پزشکی خراسان شمالی'), ('SBMU', 'علوم پزشکی بهشتی'), ('SUMS', 'علوم پزشکی شیراز'), ('IUMS', 'علوم پزشکی ایران'), ('MUI', 'علوم پزشکی اصفهان'), ('----', '-None-')], help_text='Your current university. Leave empty if not a student.', max_length=5, null=True),
        ),
    ]
