# Generated by Django 4.0.10 on 2024-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_field_alter_customuser_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='دربارۀ من'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fn_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام به فارسی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ln_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی به فارسی'),
        ),
    ]
