# Generated by Django 4.0.10 on 2024-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_about_me_customuser_fn_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_article_author',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_article_editor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_case_editor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
