# Generated by Django 4.0.10 on 2024-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(default='', verbose_name='دربارۀ من'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fn_fa',
            field=models.CharField(default='', max_length=50, verbose_name='نام به فارسی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_article_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_article_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_case_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ln_fa',
            field=models.CharField(default='', max_length=50, verbose_name='نام خانوادگی به فارسی'),
        ),
    ]
