# Generated by Django 4.0.10 on 2024-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_about_me_alter_customuser_fn_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='دربارۀ من'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fn_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام به فارسی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ln_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی به فارسی'),
        ),
    ]
