# Generated by Django 4.0.10 on 2024-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Basic Sciences', 'Basic Sciences'), ('Pathopysiology', 'Pathopysiology'), ('Medical Extern', 'Medical Extern'), ('Medical Intern', 'Medical Intern'), ('General Practicioner', 'General Practicioner'), ('Medical Resident', 'Medical Resident'), ('Medical Specialist', 'Medical Specialist'), ('Fellowship', 'Fellowship'), ('Superspecialist', 'Superspecialist')], help_text='Your current degree. Leave empty if not Medical Doctor/Student.', max_length=20, null=True),
        ),
    ]
