# Generated by Django 4.0.10 on 2024-10-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hx_cc_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_cc_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_pi_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_pi_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
