# Generated by Django 4.0.10 on 2024-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_hx_cc_ai_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hx_ddx_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_ddx_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_phe_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_phe_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_ros_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_ros_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_sum_ai_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hx_sum_ai_use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
