# Generated by Django 4.0.10 on 2025-03-29 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculi',
            name='page_title',
        ),
        migrations.AddField(
            model_name='calcate',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calcate',
            name='link',
            field=models.SlugField(default='Ehsan', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculi',
            name='html_title',
            field=models.CharField(default='Ehsan', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculi',
            name='html',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='calculi',
            name='link',
            field=models.SlugField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='calculi',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_name', models.CharField(max_length=127)),
                ('input_data', models.CharField(blank=True, max_length=255, null=True)),
                ('output', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('error_data', models.CharField(blank=True, max_length=127, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
