# Generated by Django 4.0.10 on 2025-03-30 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_department_subdepartment_studentprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculus', '0002_remove_calculi_page_title_calcate_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='calculi',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='calculi',
            name='likes',
            field=models.ManyToManyField(related_name='liked_calculus', through='calculus.CaLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calculi',
            index=models.Index(fields=['like_count'], name='calculus_ca_like_co_d22d4e_idx'),
        ),
        migrations.AddField(
            model_name='calike',
            name='calculi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculus.calculi'),
        ),
        migrations.AddField(
            model_name='calike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calike',
            index=models.Index(fields=['user', 'calculi'], name='calculus_ca_user_id_b50b51_idx'),
        ),
        migrations.AddIndex(
            model_name='calike',
            index=models.Index(fields=['calculi', 'user'], name='calculus_ca_calculi_193419_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calike',
            unique_together={('user', 'calculi')},
        ),
    ]
