# Generated by Django 5.2.5 on 2025-10-23 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculus', '0003_calike_calculi_like_count_calculi_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculi',
            name='likes',
            field=models.ManyToManyField(related_name='liked_calculus', through='calculus.CaLike', through_fields=('calculi', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
