# Generated by Django 4.0.10 on 2025-05-23 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('personal_id', models.SlugField(max_length=10, unique=True, verbose_name='کد ملی یا شمارۀ گذرنامه')),
                ('gender', models.CharField(choices=[('پسر', 'پسر'), ('دختر', 'پسر')], default='پسر', max_length=5, verbose_name='جنسیت')),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Weight Value')),
                ('weight_z', models.FloatField(default=0, verbose_name='Weight Z Score')),
                ('weight_p', models.FloatField(default=0, verbose_name='Weight Percentile')),
                ('height', models.SmallIntegerField(default=0, verbose_name='Height Value')),
                ('height_z', models.FloatField(default=0, verbose_name='Height Z Score')),
                ('height_p', models.FloatField(default=0, verbose_name='Height Percentile')),
                ('bmi', models.FloatField(default=0, verbose_name='BMI Value')),
                ('bmi_z', models.FloatField(default=0, verbose_name='BMI Z Score')),
                ('bmi_p', models.FloatField(default=0, verbose_name='BMI Percentile')),
                ('hc', models.FloatField(blank=True, default=0, null=True, verbose_name='Head Circumference Value')),
                ('hc_z', models.FloatField(default=0, verbose_name='Head Circumference Z Score')),
                ('hc_p', models.FloatField(default=0, verbose_name='Head Circumference Percentile')),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('age_months', models.FloatField(default=0, verbose_name='Age in monthes')),
                ('record_add_date', models.DateTimeField(auto_now_add=True)),
                ('record_edir_date', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.patient')),
            ],
        ),
    ]
