# Generated by Django 4.0.10 on 2025-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('پسر', 'پسر'), ('دختر', 'دختر')], default='پسر', max_length=5, verbose_name='جنسیت'),
        ),
    ]
