# Generated by Django 4.0.10 on 2025-05-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_edir_date',
            new_name='record_edit_date',
        ),
    ]
