# Generated by Django 4.0.10 on 2025-05-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_record_edir_date_record_record_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='hc_p',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Head Circumference Percentile'),
        ),
        migrations.AlterField(
            model_name='record',
            name='hc_z',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Head Circumference Z Score'),
        ),
    ]
