# Generated by Django 4.0.10 on 2025-05-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_record_hc_p_alter_record_hc_z'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_add_date',
            new_name='record_date',
        ),
    ]
