# Generated by Django 4.0.10 on 2025-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='wl_p',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight for Length Percentile'),
        ),
        migrations.AddField(
            model_name='record',
            name='wl_z',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight for Length Z Score'),
        ),
    ]
