# Generated by Django 4.0.10 on 2025-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_record_wl_p_record_wl_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='wl_p50',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight for Length P50 Value'),
        ),
    ]
