# Generated by Django 5.2.5 on 2025-10-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_patient_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-record_date']},
        ),
    ]
